extends Node


var bot_a = preload("res://tree_big.png")
var mid_a = preload("res://tree_small.png")
var top_a = preload("res://tree_tiny.png")
var bot_b = preload("res://bot_b.png")
var mid_b = preload("res://mid_b.png")
var top_b = preload("res://top_b.png")
var bot_c = preload("res://bot_c.png")
var mid_c = preload("res://mid_c.png")
var top_c = preload("res://top_c.png")
var bot_d = preload("res://bot_d.png")
var mid_d = preload("res://mid_d.png")
var top_d = preload("res://top_d.png")
var bot_e = preload("res://bot_e.png")
var mid_e = preload("res://mid_e.png")
var top_e = preload("res://top_e.png")

var one_a = preload("res://1a.png")
var one_b = preload("res://1b.png")
var one_c = preload("res://1c.png")
var two_a = preload("res://2a.png")
var two_b = preload("res://2b.png")
var two_c = preload("res://2c.png")
var thr_a = preload("res://3a.png")
var thr_b = preload("res://3b.png")
var thr_c = preload("res://3c.png")
var fou_a = preload("res://4a.png")
var fou_b = preload("res://4b.png")
var fou_c = preload("res://4c.png")
